import type { ThemePreset } from "../types/theme";

// Curated collection of famous editor / design color themes, each with a full
// light + dark palette. Rendered in the "Theme Presets" dropdown of the
// customizer and applied via the same mechanism as the tweakcn presets.
export const colorThemePresets: Record<string, ThemePreset> = {
  "dracula": {
    label: "Dracula",
    styles: {
      light: {
        background: "#f5f4fb",
        foreground: "#282a36",
        card: "#fafafd",
        "card-foreground": "#282a36",
        popover: "#fafafd",
        "popover-foreground": "#282a36",
        primary: "#7857d6",
        "primary-foreground": "#ffffff",
        secondary: "#eae9f0",
        "secondary-foreground": "#282a36",
        muted: "#eae9f0",
        "muted-foreground": "#7e7f89",
        accent: "#e3ddf6",
        "accent-foreground": "#282a36",
        destructive: "#cb3a2a",
        "destructive-foreground": "#ffffff",
        border: "#dad9df",
        input: "#dad9df",
        ring: "#7857d6",
        "chart-1": "#7857d6",
        "chart-2": "#d6398a",
        "chart-3": "#0f7a9e",
        "chart-4": "#1f8a3b",
        "chart-5": "#c26016",
        sidebar: "#eeedf3",
        "sidebar-foreground": "#282a36",
        "sidebar-primary": "#7857d6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e3ddf6",
        "sidebar-accent-foreground": "#282a36",
        "sidebar-border": "#dad9df",
        "sidebar-ring": "#7857d6",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#282a36",
        foreground: "#f8f8f2",
        card: "#333540",
        "card-foreground": "#f8f8f2",
        popover: "#333540",
        "popover-foreground": "#f8f8f2",
        primary: "#bd93f9",
        "primary-foreground": "#0a0a0a",
        secondary: "#40414c",
        "secondary-foreground": "#f8f8f2",
        muted: "#40414c",
        "muted-foreground": "#a1a1a3",
        accent: "#574d70",
        "accent-foreground": "#f8f8f2",
        destructive: "#ff5555",
        "destructive-foreground": "#ffffff",
        border: "#4a4c56",
        input: "#4a4c56",
        ring: "#bd93f9",
        "chart-1": "#bd93f9",
        "chart-2": "#ff79c6",
        "chart-3": "#8be9fd",
        "chart-4": "#50fa7b",
        "chart-5": "#ffb86c",
        sidebar: "#1e2029",
        "sidebar-foreground": "#f8f8f2",
        "sidebar-primary": "#bd93f9",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#574d70",
        "sidebar-accent-foreground": "#f8f8f2",
        "sidebar-border": "#4a4c56",
        "sidebar-ring": "#bd93f9",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "nord": {
    label: "Nord",
    styles: {
      light: {
        background: "#eceff4",
        foreground: "#2e3440",
        card: "#f6f7fa",
        "card-foreground": "#2e3440",
        popover: "#f6f7fa",
        "popover-foreground": "#2e3440",
        primary: "#5e81ac",
        "primary-foreground": "#ffffff",
        secondary: "#e1e4e9",
        "secondary-foreground": "#2e3440",
        muted: "#e1e4e9",
        "muted-foreground": "#7e838c",
        accent: "#dbe2ec",
        "accent-foreground": "#2e3440",
        destructive: "#bf616a",
        "destructive-foreground": "#ffffff",
        border: "#d2d5d9",
        input: "#d2d5d9",
        ring: "#5e81ac",
        "chart-1": "#5e81ac",
        "chart-2": "#81a1c1",
        "chart-3": "#8fbcbb",
        "chart-4": "#a3be8c",
        "chart-5": "#b48ead",
        sidebar: "#e5e8ed",
        "sidebar-foreground": "#2e3440",
        "sidebar-primary": "#5e81ac",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#dbe2ec",
        "sidebar-accent-foreground": "#2e3440",
        "sidebar-border": "#d2d5d9",
        "sidebar-ring": "#5e81ac",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#2e3440",
        foreground: "#eceff4",
        card: "#383e4a",
        "card-foreground": "#eceff4",
        popover: "#383e4a",
        "popover-foreground": "#eceff4",
        primary: "#88c0d0",
        "primary-foreground": "#0a0a0a",
        secondary: "#454a55",
        "secondary-foreground": "#eceff4",
        muted: "#454a55",
        "muted-foreground": "#9ca0a8",
        accent: "#4d606d",
        "accent-foreground": "#eceff4",
        destructive: "#bf616a",
        "destructive-foreground": "#ffffff",
        border: "#4f545f",
        input: "#4f545f",
        ring: "#88c0d0",
        "chart-1": "#88c0d0",
        "chart-2": "#81a1c1",
        "chart-3": "#5e81ac",
        "chart-4": "#a3be8c",
        "chart-5": "#b48ead",
        sidebar: "#232730",
        "sidebar-foreground": "#eceff4",
        "sidebar-primary": "#88c0d0",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#4d606d",
        "sidebar-accent-foreground": "#eceff4",
        "sidebar-border": "#4f545f",
        "sidebar-ring": "#88c0d0",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "solarized": {
    label: "Solarized",
    styles: {
      light: {
        background: "#fdf6e3",
        foreground: "#586e75",
        card: "#fefbf1",
        "card-foreground": "#586e75",
        popover: "#fefbf1",
        "popover-foreground": "#586e75",
        primary: "#268bd2",
        "primary-foreground": "#ffffff",
        secondary: "#f2ebd9",
        "secondary-foreground": "#586e75",
        muted: "#f2ebd9",
        "muted-foreground": "#9da7a3",
        accent: "#d7e7eb",
        "accent-foreground": "#586e75",
        destructive: "#dc322f",
        "destructive-foreground": "#ffffff",
        border: "#e1dbca",
        input: "#e1dbca",
        ring: "#268bd2",
        "chart-1": "#268bd2",
        "chart-2": "#2aa198",
        "chart-3": "#859900",
        "chart-4": "#cb4b16",
        "chart-5": "#d33682",
        sidebar: "#f5efdc",
        "sidebar-foreground": "#586e75",
        "sidebar-primary": "#268bd2",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d7e7eb",
        "sidebar-accent-foreground": "#586e75",
        "sidebar-border": "#e1dbca",
        "sidebar-ring": "#268bd2",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#002b36",
        foreground: "#93a1a1",
        card: "#0d3640",
        "card-foreground": "#93a1a1",
        popover: "#0d3640",
        "popover-foreground": "#93a1a1",
        primary: "#268bd2",
        "primary-foreground": "#ffffff",
        secondary: "#1c424c",
        "secondary-foreground": "#93a1a1",
        muted: "#1c424c",
        "muted-foreground": "#556f74",
        accent: "#144c66",
        "accent-foreground": "#93a1a1",
        destructive: "#dc322f",
        "destructive-foreground": "#ffffff",
        border: "#294d56",
        input: "#294d56",
        ring: "#268bd2",
        "chart-1": "#268bd2",
        "chart-2": "#2aa198",
        "chart-3": "#859900",
        "chart-4": "#b58900",
        "chart-5": "#6c71c4",
        sidebar: "#002029",
        "sidebar-foreground": "#93a1a1",
        "sidebar-primary": "#268bd2",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#144c66",
        "sidebar-accent-foreground": "#93a1a1",
        "sidebar-border": "#294d56",
        "sidebar-ring": "#268bd2",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "gruvbox": {
    label: "Gruvbox",
    styles: {
      light: {
        background: "#fbf1c7",
        foreground: "#3c3836",
        card: "#fdf8e3",
        "card-foreground": "#3c3836",
        popover: "#fdf8e3",
        "popover-foreground": "#3c3836",
        primary: "#d65d0e",
        "primary-foreground": "#ffffff",
        secondary: "#f0e6be",
        "secondary-foreground": "#3c3836",
        muted: "#f0e6be",
        "muted-foreground": "#8c8673",
        accent: "#f6dcbd",
        "accent-foreground": "#3c3836",
        destructive: "#cc241d",
        "destructive-foreground": "#ffffff",
        border: "#dfd6b1",
        input: "#dfd6b1",
        ring: "#d65d0e",
        "chart-1": "#d65d0e",
        "chart-2": "#d79921",
        "chart-3": "#98971a",
        "chart-4": "#689d6a",
        "chart-5": "#458588",
        sidebar: "#f3eac1",
        "sidebar-foreground": "#3c3836",
        "sidebar-primary": "#d65d0e",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f6dcbd",
        "sidebar-accent-foreground": "#3c3836",
        "sidebar-border": "#dfd6b1",
        "sidebar-ring": "#d65d0e",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#282828",
        foreground: "#ebdbb2",
        card: "#333333",
        "card-foreground": "#ebdbb2",
        popover: "#333333",
        "popover-foreground": "#ebdbb2",
        primary: "#fe8019",
        "primary-foreground": "#0a0a0a",
        secondary: "#404040",
        "secondary-foreground": "#ebdbb2",
        muted: "#404040",
        "muted-foreground": "#999078",
        accent: "#68472c",
        "accent-foreground": "#ebdbb2",
        destructive: "#fb4934",
        "destructive-foreground": "#ffffff",
        border: "#4a4a4a",
        input: "#4a4a4a",
        ring: "#fe8019",
        "chart-1": "#fe8019",
        "chart-2": "#fabd2f",
        "chart-3": "#b8bb26",
        "chart-4": "#8ec07c",
        "chart-5": "#83a598",
        sidebar: "#1e1e1e",
        "sidebar-foreground": "#ebdbb2",
        "sidebar-primary": "#fe8019",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#68472c",
        "sidebar-accent-foreground": "#ebdbb2",
        "sidebar-border": "#4a4a4a",
        "sidebar-ring": "#fe8019",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "one-dark": {
    label: "One Dark",
    styles: {
      light: {
        background: "#fafafa",
        foreground: "#383a42",
        card: "#fdfdfd",
        "card-foreground": "#383a42",
        popover: "#fdfdfd",
        "popover-foreground": "#383a42",
        primary: "#4078f2",
        "primary-foreground": "#ffffff",
        secondary: "#efefef",
        "secondary-foreground": "#383a42",
        muted: "#efefef",
        "muted-foreground": "#898b8f",
        accent: "#dbe5fb",
        "accent-foreground": "#383a42",
        destructive: "#e45649",
        "destructive-foreground": "#ffffff",
        border: "#dfdfdf",
        input: "#dfdfdf",
        ring: "#4078f2",
        "chart-1": "#4078f2",
        "chart-2": "#a626a4",
        "chart-3": "#50a14f",
        "chart-4": "#c18401",
        "chart-5": "#0184bc",
        sidebar: "#f3f3f3",
        "sidebar-foreground": "#383a42",
        "sidebar-primary": "#4078f2",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#dbe5fb",
        "sidebar-accent-foreground": "#383a42",
        "sidebar-border": "#dfdfdf",
        "sidebar-ring": "#4078f2",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#282c34",
        foreground: "#abb2bf",
        card: "#33373e",
        "card-foreground": "#abb2bf",
        popover: "#33373e",
        "popover-foreground": "#abb2bf",
        primary: "#61afef",
        "primary-foreground": "#0a0a0a",
        secondary: "#40434a",
        "secondary-foreground": "#abb2bf",
        muted: "#40434a",
        "muted-foreground": "#747a85",
        accent: "#3f566c",
        "accent-foreground": "#abb2bf",
        destructive: "#e06c75",
        "destructive-foreground": "#ffffff",
        border: "#4a4e54",
        input: "#4a4e54",
        ring: "#61afef",
        "chart-1": "#61afef",
        "chart-2": "#c678dd",
        "chart-3": "#98c379",
        "chart-4": "#e5c07b",
        "chart-5": "#56b6c2",
        sidebar: "#1e2127",
        "sidebar-foreground": "#abb2bf",
        "sidebar-primary": "#61afef",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#3f566c",
        "sidebar-accent-foreground": "#abb2bf",
        "sidebar-border": "#4a4e54",
        "sidebar-ring": "#61afef",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "monokai": {
    label: "Monokai",
    styles: {
      light: {
        background: "#fafafa",
        foreground: "#272822",
        card: "#fdfdfd",
        "card-foreground": "#272822",
        popover: "#fdfdfd",
        "popover-foreground": "#272822",
        primary: "#e5218a",
        "primary-foreground": "#ffffff",
        secondary: "#efefef",
        "secondary-foreground": "#272822",
        muted: "#efefef",
        "muted-foreground": "#80807d",
        accent: "#f9d5e8",
        "accent-foreground": "#272822",
        destructive: "#d0454c",
        "destructive-foreground": "#ffffff",
        border: "#dfdfdf",
        input: "#dfdfdf",
        ring: "#e5218a",
        "chart-1": "#e5218a",
        "chart-2": "#4c9a1e",
        "chart-3": "#1c94b3",
        "chart-4": "#d97a15",
        "chart-5": "#7b52d1",
        sidebar: "#f3f3f3",
        "sidebar-foreground": "#272822",
        "sidebar-primary": "#e5218a",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f9d5e8",
        "sidebar-accent-foreground": "#272822",
        "sidebar-border": "#dfdfdf",
        "sidebar-ring": "#e5218a",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#272822",
        foreground: "#f8f8f2",
        card: "#32332d",
        "card-foreground": "#f8f8f2",
        popover: "#32332d",
        "popover-foreground": "#f8f8f2",
        primary: "#f92672",
        "primary-foreground": "#ffffff",
        secondary: "#3f403a",
        "secondary-foreground": "#f8f8f2",
        muted: "#3f403a",
        "muted-foreground": "#a0a19b",
        accent: "#66303f",
        "accent-foreground": "#f8f8f2",
        destructive: "#e5493f",
        "destructive-foreground": "#ffffff",
        border: "#4a4a45",
        input: "#4a4a45",
        ring: "#f92672",
        "chart-1": "#f92672",
        "chart-2": "#a6e22e",
        "chart-3": "#66d9ef",
        "chart-4": "#fd971f",
        "chart-5": "#ae81ff",
        sidebar: "#1d1e1a",
        "sidebar-foreground": "#f8f8f2",
        "sidebar-primary": "#f92672",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#66303f",
        "sidebar-accent-foreground": "#f8f8f2",
        "sidebar-border": "#4a4a45",
        "sidebar-ring": "#f92672",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "tokyo-night": {
    label: "Tokyo Night",
    styles: {
      light: {
        background: "#e1e2e7",
        foreground: "#343b58",
        card: "#f0f1f3",
        "card-foreground": "#343b58",
        popover: "#f0f1f3",
        "popover-foreground": "#343b58",
        primary: "#2e7de9",
        "primary-foreground": "#ffffff",
        secondary: "#d7d8dd",
        "secondary-foreground": "#343b58",
        muted: "#d7d8dd",
        "muted-foreground": "#7d8194",
        accent: "#cddcf1",
        "accent-foreground": "#343b58",
        destructive: "#f52a65",
        "destructive-foreground": "#ffffff",
        border: "#c8c9ce",
        input: "#c8c9ce",
        ring: "#2e7de9",
        "chart-1": "#2e7de9",
        "chart-2": "#9854f1",
        "chart-3": "#007197",
        "chart-4": "#587539",
        "chart-5": "#8c6c3e",
        sidebar: "#dadbe0",
        "sidebar-foreground": "#343b58",
        "sidebar-primary": "#2e7de9",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#cddcf1",
        "sidebar-accent-foreground": "#343b58",
        "sidebar-border": "#c8c9ce",
        "sidebar-ring": "#2e7de9",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1a1b26",
        foreground: "#c0caf5",
        card: "#252631",
        "card-foreground": "#c0caf5",
        popover: "#252631",
        "popover-foreground": "#c0caf5",
        primary: "#7aa2f7",
        "primary-foreground": "#0a0a0a",
        secondary: "#33343e",
        "secondary-foreground": "#c0caf5",
        muted: "#33343e",
        "muted-foreground": "#7a819e",
        accent: "#3b4664",
        "accent-foreground": "#c0caf5",
        destructive: "#f7768e",
        "destructive-foreground": "#ffffff",
        border: "#3f3f49",
        input: "#3f3f49",
        ring: "#7aa2f7",
        "chart-1": "#7aa2f7",
        "chart-2": "#bb9af7",
        "chart-3": "#7dcfff",
        "chart-4": "#9ece6a",
        "chart-5": "#e0af68",
        sidebar: "#14141d",
        "sidebar-foreground": "#c0caf5",
        "sidebar-primary": "#7aa2f7",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#3b4664",
        "sidebar-accent-foreground": "#c0caf5",
        "sidebar-border": "#3f3f49",
        "sidebar-ring": "#7aa2f7",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "rose-pine": {
    label: "Rose Pine",
    styles: {
      light: {
        background: "#faf4ed",
        foreground: "#575279",
        card: "#fdfaf6",
        "card-foreground": "#575279",
        popover: "#fdfaf6",
        "popover-foreground": "#575279",
        primary: "#907aa9",
        "primary-foreground": "#ffffff",
        secondary: "#efe9e2",
        "secondary-foreground": "#575279",
        muted: "#efe9e2",
        "muted-foreground": "#9b96aa",
        accent: "#e9e3e8",
        "accent-foreground": "#575279",
        destructive: "#b4637a",
        "destructive-foreground": "#ffffff",
        border: "#dfd9d3",
        input: "#dfd9d3",
        ring: "#907aa9",
        "chart-1": "#907aa9",
        "chart-2": "#d7827e",
        "chart-3": "#56949f",
        "chart-4": "#286983",
        "chart-5": "#ea9d34",
        sidebar: "#f3ede6",
        "sidebar-foreground": "#575279",
        "sidebar-primary": "#907aa9",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e9e3e8",
        "sidebar-accent-foreground": "#575279",
        "sidebar-border": "#dfd9d3",
        "sidebar-ring": "#907aa9",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#191724",
        foreground: "#e0def4",
        card: "#25232f",
        "card-foreground": "#e0def4",
        popover: "#25232f",
        "popover-foreground": "#e0def4",
        primary: "#c4a7e7",
        "primary-foreground": "#0a0a0a",
        secondary: "#32313c",
        "secondary-foreground": "#e0def4",
        muted: "#32313c",
        "muted-foreground": "#8c8a9d",
        accent: "#4e455f",
        "accent-foreground": "#e0def4",
        destructive: "#eb6f92",
        "destructive-foreground": "#ffffff",
        border: "#3e3c47",
        input: "#3e3c47",
        ring: "#c4a7e7",
        "chart-1": "#c4a7e7",
        "chart-2": "#ebbcba",
        "chart-3": "#9ccfd8",
        "chart-4": "#31748f",
        "chart-5": "#f6c177",
        sidebar: "#13111b",
        "sidebar-foreground": "#e0def4",
        "sidebar-primary": "#c4a7e7",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#4e455f",
        "sidebar-accent-foreground": "#e0def4",
        "sidebar-border": "#3e3c47",
        "sidebar-ring": "#c4a7e7",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "everforest": {
    label: "Everforest",
    styles: {
      light: {
        background: "#fdf6e3",
        foreground: "#5c6a72",
        card: "#fefbf1",
        "card-foreground": "#5c6a72",
        popover: "#fefbf1",
        "popover-foreground": "#5c6a72",
        primary: "#8da101",
        "primary-foreground": "#ffffff",
        secondary: "#f2ebd9",
        "secondary-foreground": "#5c6a72",
        muted: "#f2ebd9",
        "muted-foreground": "#a0a5a1",
        accent: "#eaebc6",
        "accent-foreground": "#5c6a72",
        destructive: "#f85552",
        "destructive-foreground": "#ffffff",
        border: "#e1dbca",
        input: "#e1dbca",
        ring: "#8da101",
        "chart-1": "#8da101",
        "chart-2": "#35a77c",
        "chart-3": "#3a94c5",
        "chart-4": "#dfa000",
        "chart-5": "#df69ba",
        sidebar: "#f5efdc",
        "sidebar-foreground": "#5c6a72",
        "sidebar-primary": "#8da101",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#eaebc6",
        "sidebar-accent-foreground": "#5c6a72",
        "sidebar-border": "#e1dbca",
        "sidebar-ring": "#8da101",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#2d353b",
        foreground: "#d3c6aa",
        card: "#383f45",
        "card-foreground": "#d3c6aa",
        popover: "#383f45",
        "popover-foreground": "#d3c6aa",
        primary: "#a7c080",
        "primary-foreground": "#0a0a0a",
        secondary: "#444b51",
        "secondary-foreground": "#d3c6aa",
        muted: "#444b51",
        "muted-foreground": "#8d897b",
        accent: "#556154",
        "accent-foreground": "#d3c6aa",
        destructive: "#e67e80",
        "destructive-foreground": "#ffffff",
        border: "#4f555a",
        input: "#4f555a",
        ring: "#a7c080",
        "chart-1": "#a7c080",
        "chart-2": "#83c092",
        "chart-3": "#7fbbb3",
        "chart-4": "#dbbc7f",
        "chart-5": "#d699b6",
        sidebar: "#22282c",
        "sidebar-foreground": "#d3c6aa",
        "sidebar-primary": "#a7c080",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#556154",
        "sidebar-accent-foreground": "#d3c6aa",
        "sidebar-border": "#4f555a",
        "sidebar-ring": "#a7c080",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "ayu": {
    label: "Ayu",
    styles: {
      light: {
        background: "#fcfcfc",
        foreground: "#5c6166",
        card: "#fefefe",
        "card-foreground": "#5c6166",
        popover: "#fefefe",
        "popover-foreground": "#5c6166",
        primary: "#fa8d3e",
        "primary-foreground": "#0a0a0a",
        secondary: "#f1f1f1",
        "secondary-foreground": "#5c6166",
        muted: "#f1f1f1",
        "muted-foreground": "#9fa2a5",
        accent: "#fdeadb",
        "accent-foreground": "#5c6166",
        destructive: "#e65050",
        "destructive-foreground": "#ffffff",
        border: "#e0e0e0",
        input: "#e0e0e0",
        ring: "#fa8d3e",
        "chart-1": "#fa8d3e",
        "chart-2": "#399ee6",
        "chart-3": "#86b300",
        "chart-4": "#a37acc",
        "chart-5": "#4cbf99",
        sidebar: "#f4f4f4",
        "sidebar-foreground": "#5c6166",
        "sidebar-primary": "#fa8d3e",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#fdeadb",
        "sidebar-accent-foreground": "#5c6166",
        "sidebar-border": "#e0e0e0",
        "sidebar-ring": "#fa8d3e",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0b0e14",
        foreground: "#bfbdb6",
        card: "#171a20",
        "card-foreground": "#bfbdb6",
        popover: "#171a20",
        "popover-foreground": "#bfbdb6",
        primary: "#ffb454",
        "primary-foreground": "#0a0a0a",
        secondary: "#26292e",
        "secondary-foreground": "#bfbdb6",
        muted: "#26292e",
        "muted-foreground": "#737472",
        accent: "#53422e",
        "accent-foreground": "#bfbdb6",
        destructive: "#f26d78",
        "destructive-foreground": "#ffffff",
        border: "#32353a",
        input: "#32353a",
        ring: "#ffb454",
        "chart-1": "#ffb454",
        "chart-2": "#59c2ff",
        "chart-3": "#aad94c",
        "chart-4": "#d2a6ff",
        "chart-5": "#95e6cb",
        sidebar: "#080b0f",
        "sidebar-foreground": "#bfbdb6",
        "sidebar-primary": "#ffb454",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#53422e",
        "sidebar-accent-foreground": "#bfbdb6",
        "sidebar-border": "#32353a",
        "sidebar-ring": "#ffb454",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "github": {
    label: "GitHub",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#24292f",
        card: "#ffffff",
        "card-foreground": "#24292f",
        popover: "#ffffff",
        "popover-foreground": "#24292f",
        primary: "#0969da",
        "primary-foreground": "#ffffff",
        secondary: "#f4f4f4",
        "secondary-foreground": "#24292f",
        muted: "#f4f4f4",
        "muted-foreground": "#808386",
        accent: "#d3e4f8",
        "accent-foreground": "#24292f",
        destructive: "#cf222e",
        "destructive-foreground": "#ffffff",
        border: "#e3e3e3",
        input: "#e3e3e3",
        ring: "#0969da",
        "chart-1": "#0969da",
        "chart-2": "#1a7f37",
        "chart-3": "#9a6700",
        "chart-4": "#8250df",
        "chart-5": "#bf3989",
        sidebar: "#f7f7f7",
        "sidebar-foreground": "#24292f",
        "sidebar-primary": "#0969da",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d3e4f8",
        "sidebar-accent-foreground": "#24292f",
        "sidebar-border": "#e3e3e3",
        "sidebar-ring": "#0969da",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0d1117",
        foreground: "#c9d1d9",
        card: "#191d23",
        "card-foreground": "#c9d1d9",
        popover: "#191d23",
        "popover-foreground": "#c9d1d9",
        primary: "#58a6ff",
        "primary-foreground": "#0a0a0a",
        secondary: "#282b31",
        "secondary-foreground": "#c9d1d9",
        muted: "#282b31",
        "muted-foreground": "#7a8088",
        accent: "#29415c",
        "accent-foreground": "#c9d1d9",
        destructive: "#f85149",
        "destructive-foreground": "#ffffff",
        border: "#34373c",
        input: "#34373c",
        ring: "#58a6ff",
        "chart-1": "#58a6ff",
        "chart-2": "#3fb950",
        "chart-3": "#d29922",
        "chart-4": "#bc8cff",
        "chart-5": "#f778ba",
        sidebar: "#0a0d11",
        "sidebar-foreground": "#c9d1d9",
        "sidebar-primary": "#58a6ff",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#29415c",
        "sidebar-accent-foreground": "#c9d1d9",
        "sidebar-border": "#34373c",
        "sidebar-ring": "#58a6ff",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "synthwave-84": {
    label: "Synthwave '84",
    styles: {
      light: {
        background: "#f4f2fb",
        foreground: "#241b2f",
        card: "#faf9fd",
        "card-foreground": "#241b2f",
        popover: "#faf9fd",
        "popover-foreground": "#241b2f",
        primary: "#d6249a",
        "primary-foreground": "#ffffff",
        secondary: "#e9e7f0",
        "secondary-foreground": "#241b2f",
        muted: "#e9e7f0",
        "muted-foreground": "#7b7585",
        accent: "#f4d3eb",
        "accent-foreground": "#241b2f",
        destructive: "#e5395b",
        "destructive-foreground": "#ffffff",
        border: "#d9d7df",
        input: "#d9d7df",
        ring: "#d6249a",
        "chart-1": "#d6249a",
        "chart-2": "#0aa3a0",
        "chart-3": "#c99b12",
        "chart-4": "#17a06a",
        "chart-5": "#7b52c9",
        sidebar: "#edebf3",
        "sidebar-foreground": "#241b2f",
        "sidebar-primary": "#d6249a",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f4d3eb",
        "sidebar-accent-foreground": "#241b2f",
        "sidebar-border": "#d9d7df",
        "sidebar-ring": "#d6249a",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.625rem",
      },
      dark: {
        background: "#262335",
        foreground: "#ffffff",
        card: "#312e3f",
        "card-foreground": "#ffffff",
        popover: "#312e3f",
        "popover-foreground": "#ffffff",
        primary: "#ff7edb",
        "primary-foreground": "#0a0a0a",
        secondary: "#3e3b4b",
        "secondary-foreground": "#ffffff",
        muted: "#3e3b4b",
        "muted-foreground": "#a4a3aa",
        accent: "#674368",
        "accent-foreground": "#ffffff",
        destructive: "#fe4450",
        "destructive-foreground": "#ffffff",
        border: "#494655",
        input: "#494655",
        ring: "#ff7edb",
        "chart-1": "#ff7edb",
        "chart-2": "#36f9f6",
        "chart-3": "#fede5d",
        "chart-4": "#72f1b8",
        "chart-5": "#b893ce",
        sidebar: "#1d1a28",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#ff7edb",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#674368",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#494655",
        "sidebar-ring": "#ff7edb",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.625rem",
      }
    }
  },

  "night-owl": {
    label: "Night Owl",
    styles: {
      light: {
        background: "#fbfbfb",
        foreground: "#403f53",
        card: "#fdfdfd",
        "card-foreground": "#403f53",
        popover: "#fdfdfd",
        "popover-foreground": "#403f53",
        primary: "#0c8fb8",
        "primary-foreground": "#ffffff",
        secondary: "#f0f0f0",
        "secondary-foreground": "#403f53",
        muted: "#f0f0f0",
        "muted-foreground": "#8f8e9a",
        accent: "#d2e9f1",
        "accent-foreground": "#403f53",
        destructive: "#d3423e",
        "destructive-foreground": "#ffffff",
        border: "#dfdfdf",
        input: "#dfdfdf",
        ring: "#0c8fb8",
        "chart-1": "#0c8fb8",
        "chart-2": "#994cc3",
        "chart-3": "#4876d6",
        "chart-4": "#08916a",
        "chart-5": "#daaa01",
        sidebar: "#f3f3f3",
        "sidebar-foreground": "#403f53",
        "sidebar-primary": "#0c8fb8",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d2e9f1",
        "sidebar-accent-foreground": "#403f53",
        "sidebar-border": "#dfdfdf",
        "sidebar-ring": "#0c8fb8",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#011627",
        foreground: "#d6deeb",
        card: "#0e2232",
        "card-foreground": "#d6deeb",
        popover: "#0e2232",
        "popover-foreground": "#d6deeb",
        primary: "#82aaff",
        "primary-foreground": "#0a0a0a",
        secondary: "#1d303f",
        "secondary-foreground": "#d6deeb",
        muted: "#1d303f",
        "muted-foreground": "#7d8a99",
        accent: "#2c4567",
        "accent-foreground": "#d6deeb",
        destructive: "#ef5350",
        "destructive-foreground": "#ffffff",
        border: "#2a3b4a",
        input: "#2a3b4a",
        ring: "#82aaff",
        "chart-1": "#82aaff",
        "chart-2": "#c792ea",
        "chart-3": "#addb67",
        "chart-4": "#ecc48d",
        "chart-5": "#7fdbca",
        sidebar: "#01111d",
        "sidebar-foreground": "#d6deeb",
        "sidebar-primary": "#82aaff",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#2c4567",
        "sidebar-accent-foreground": "#d6deeb",
        "sidebar-border": "#2a3b4a",
        "sidebar-ring": "#82aaff",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "material-ocean": {
    label: "Material Ocean",
    styles: {
      light: {
        background: "#fafafa",
        foreground: "#546e7a",
        card: "#fdfdfd",
        "card-foreground": "#546e7a",
        popover: "#fdfdfd",
        "popover-foreground": "#546e7a",
        primary: "#6182b8",
        "primary-foreground": "#ffffff",
        secondary: "#efefef",
        "secondary-foreground": "#546e7a",
        muted: "#efefef",
        "muted-foreground": "#9aa9b0",
        accent: "#e1e7f1",
        "accent-foreground": "#546e7a",
        destructive: "#e53935",
        "destructive-foreground": "#ffffff",
        border: "#dfdfdf",
        input: "#dfdfdf",
        ring: "#6182b8",
        "chart-1": "#6182b8",
        "chart-2": "#7c4dff",
        "chart-3": "#91b859",
        "chart-4": "#f6a434",
        "chart-5": "#39adb5",
        sidebar: "#f3f3f3",
        "sidebar-foreground": "#546e7a",
        "sidebar-primary": "#6182b8",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e1e7f1",
        "sidebar-accent-foreground": "#546e7a",
        "sidebar-border": "#dfdfdf",
        "sidebar-ring": "#6182b8",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0f111a",
        foreground: "#a6accd",
        card: "#1b1d25",
        "card-foreground": "#a6accd",
        popover: "#1b1d25",
        "popover-foreground": "#a6accd",
        primary: "#82aaff",
        "primary-foreground": "#0a0a0a",
        secondary: "#292b33",
        "secondary-foreground": "#a6accd",
        muted: "#292b33",
        "muted-foreground": "#676b82",
        accent: "#36425e",
        "accent-foreground": "#a6accd",
        destructive: "#f07178",
        "destructive-foreground": "#ffffff",
        border: "#35373f",
        input: "#35373f",
        ring: "#82aaff",
        "chart-1": "#82aaff",
        "chart-2": "#c792ea",
        "chart-3": "#c3e88d",
        "chart-4": "#ffcb6b",
        "chart-5": "#89ddff",
        sidebar: "#0b0d14",
        "sidebar-foreground": "#a6accd",
        "sidebar-primary": "#82aaff",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#36425e",
        "sidebar-accent-foreground": "#a6accd",
        "sidebar-border": "#35373f",
        "sidebar-ring": "#82aaff",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "kanagawa": {
    label: "Kanagawa",
    styles: {
      light: {
        background: "#f2ecbc",
        foreground: "#545464",
        card: "#f9f6de",
        "card-foreground": "#545464",
        popover: "#f9f6de",
        "popover-foreground": "#545464",
        primary: "#4d699b",
        "primary-foreground": "#ffffff",
        secondary: "#e7e1b4",
        "secondary-foreground": "#545464",
        muted: "#e7e1b4",
        "muted-foreground": "#969489",
        accent: "#daddd2",
        "accent-foreground": "#545464",
        destructive: "#c84053",
        "destructive-foreground": "#ffffff",
        border: "#d7d2a7",
        input: "#d7d2a7",
        ring: "#4d699b",
        "chart-1": "#4d699b",
        "chart-2": "#6f894e",
        "chart-3": "#77713f",
        "chart-4": "#cc6d00",
        "chart-5": "#624c83",
        sidebar: "#ebe5b6",
        "sidebar-foreground": "#545464",
        "sidebar-primary": "#4d699b",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#daddd2",
        "sidebar-accent-foreground": "#545464",
        "sidebar-border": "#d7d2a7",
        "sidebar-ring": "#4d699b",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1f1f28",
        foreground: "#dcd7ba",
        card: "#2a2a33",
        "card-foreground": "#dcd7ba",
        popover: "#2a2a33",
        "popover-foreground": "#dcd7ba",
        primary: "#7e9cd8",
        "primary-foreground": "#ffffff",
        secondary: "#383840",
        "secondary-foreground": "#dcd7ba",
        muted: "#383840",
        "muted-foreground": "#8d8a7d",
        accent: "#40485e",
        "accent-foreground": "#dcd7ba",
        destructive: "#e46876",
        "destructive-foreground": "#ffffff",
        border: "#43434a",
        input: "#43434a",
        ring: "#7e9cd8",
        "chart-1": "#7e9cd8",
        "chart-2": "#98bb6c",
        "chart-3": "#e6c384",
        "chart-4": "#ff9e3b",
        "chart-5": "#957fb8",
        sidebar: "#17171e",
        "sidebar-foreground": "#dcd7ba",
        "sidebar-primary": "#7e9cd8",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#40485e",
        "sidebar-accent-foreground": "#dcd7ba",
        "sidebar-border": "#43434a",
        "sidebar-ring": "#7e9cd8",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "cobalt2": {
    label: "Cobalt2",
    styles: {
      light: {
        background: "#eef4f8",
        foreground: "#193549",
        card: "#f7fafc",
        "card-foreground": "#193549",
        popover: "#f7fafc",
        "popover-foreground": "#193549",
        primary: "#0062cc",
        "primary-foreground": "#ffffff",
        secondary: "#e3e9ed",
        "secondary-foreground": "#193549",
        muted: "#e3e9ed",
        "muted-foreground": "#728593",
        accent: "#cbdff3",
        "accent-foreground": "#193549",
        destructive: "#e01563",
        "destructive-foreground": "#ffffff",
        border: "#d4d9dd",
        input: "#d4d9dd",
        ring: "#0062cc",
        "chart-1": "#0062cc",
        "chart-2": "#c79a00",
        "chart-3": "#2a9d00",
        "chart-4": "#d97a00",
        "chart-5": "#0aa0b0",
        sidebar: "#e7edf1",
        "sidebar-foreground": "#193549",
        "sidebar-primary": "#0062cc",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#cbdff3",
        "sidebar-accent-foreground": "#193549",
        "sidebar-border": "#d4d9dd",
        "sidebar-ring": "#0062cc",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.3rem",
      },
      dark: {
        background: "#193549",
        foreground: "#ffffff",
        card: "#253f52",
        "card-foreground": "#ffffff",
        popover: "#253f52",
        "popover-foreground": "#ffffff",
        primary: "#ffc600",
        "primary-foreground": "#0a0a0a",
        secondary: "#324b5d",
        "secondary-foreground": "#ffffff",
        muted: "#324b5d",
        "muted-foreground": "#9eaab3",
        accent: "#5e623d",
        "accent-foreground": "#ffffff",
        destructive: "#ff2c70",
        "destructive-foreground": "#ffffff",
        border: "#3e5566",
        input: "#3e5566",
        ring: "#ffc600",
        "chart-1": "#ffc600",
        "chart-2": "#0088ff",
        "chart-3": "#3ad900",
        "chart-4": "#ff9d00",
        "chart-5": "#80fcff",
        sidebar: "#132837",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#ffc600",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#5e623d",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#3e5566",
        "sidebar-ring": "#ffc600",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.3rem",
      }
    }
  },

  "horizon": {
    label: "Horizon",
    styles: {
      light: {
        background: "#fdf0ed",
        foreground: "#16161c",
        card: "#fef8f6",
        "card-foreground": "#16161c",
        popover: "#fef8f6",
        "popover-foreground": "#16161c",
        primary: "#e0396c",
        "primary-foreground": "#ffffff",
        secondary: "#f2e5e2",
        "secondary-foreground": "#16161c",
        muted: "#f2e5e2",
        "muted-foreground": "#777274",
        accent: "#f9d6dd",
        "accent-foreground": "#16161c",
        destructive: "#f43e5c",
        "destructive-foreground": "#ffffff",
        border: "#e1d6d3",
        input: "#e1d6d3",
        ring: "#e0396c",
        "chart-1": "#e0396c",
        "chart-2": "#d98a5b",
        "chart-3": "#1eae7f",
        "chart-4": "#1ba0be",
        "chart-5": "#a24fc4",
        sidebar: "#f5e9e6",
        "sidebar-foreground": "#16161c",
        "sidebar-primary": "#e0396c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f9d6dd",
        "sidebar-accent-foreground": "#16161c",
        "sidebar-border": "#e1d6d3",
        "sidebar-ring": "#e0396c",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1c1e26",
        foreground: "#d5d8da",
        card: "#272931",
        "card-foreground": "#d5d8da",
        popover: "#272931",
        "popover-foreground": "#d5d8da",
        primary: "#e95678",
        "primary-foreground": "#ffffff",
        secondary: "#35373e",
        "secondary-foreground": "#d5d8da",
        muted: "#35373e",
        "muted-foreground": "#878a8e",
        accent: "#593543",
        "accent-foreground": "#d5d8da",
        destructive: "#f43e5c",
        "destructive-foreground": "#ffffff",
        border: "#404249",
        input: "#404249",
        ring: "#e95678",
        "chart-1": "#e95678",
        "chart-2": "#fab795",
        "chart-3": "#29d398",
        "chart-4": "#26bbd9",
        "chart-5": "#b877db",
        sidebar: "#15171d",
        "sidebar-foreground": "#d5d8da",
        "sidebar-primary": "#e95678",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#593543",
        "sidebar-accent-foreground": "#d5d8da",
        "sidebar-border": "#404249",
        "sidebar-ring": "#e95678",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "oceanic-next": {
    label: "Oceanic Next",
    styles: {
      light: {
        background: "#f2f5f7",
        foreground: "#343d46",
        card: "#f9fafb",
        "card-foreground": "#343d46",
        popover: "#f9fafb",
        "popover-foreground": "#343d46",
        primary: "#4e82b4",
        "primary-foreground": "#ffffff",
        secondary: "#e7eaec",
        "secondary-foreground": "#343d46",
        muted: "#e7eaec",
        "muted-foreground": "#848a90",
        accent: "#dae4ee",
        "accent-foreground": "#343d46",
        destructive: "#d9484f",
        "destructive-foreground": "#ffffff",
        border: "#d7dadc",
        input: "#d7dadc",
        ring: "#4e82b4",
        "chart-1": "#4e82b4",
        "chart-2": "#3f9e9e",
        "chart-3": "#5a9e55",
        "chart-4": "#d99b2b",
        "chart-5": "#a659a6",
        sidebar: "#ebeef0",
        "sidebar-foreground": "#343d46",
        "sidebar-primary": "#4e82b4",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#dae4ee",
        "sidebar-accent-foreground": "#343d46",
        "sidebar-border": "#d7dadc",
        "sidebar-ring": "#4e82b4",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1b2b34",
        foreground: "#cdd3de",
        card: "#26363e",
        "card-foreground": "#cdd3de",
        popover: "#26363e",
        "popover-foreground": "#cdd3de",
        primary: "#6699cc",
        "primary-foreground": "#ffffff",
        secondary: "#34424a",
        "secondary-foreground": "#cdd3de",
        muted: "#34424a",
        "muted-foreground": "#828c97",
        accent: "#375063",
        "accent-foreground": "#cdd3de",
        destructive: "#ec5f67",
        "destructive-foreground": "#ffffff",
        border: "#3f4d54",
        input: "#3f4d54",
        ring: "#6699cc",
        "chart-1": "#6699cc",
        "chart-2": "#5fb3b3",
        "chart-3": "#99c794",
        "chart-4": "#fac863",
        "chart-5": "#c594c5",
        sidebar: "#142027",
        "sidebar-foreground": "#cdd3de",
        "sidebar-primary": "#6699cc",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#375063",
        "sidebar-accent-foreground": "#cdd3de",
        "sidebar-border": "#3f4d54",
        "sidebar-ring": "#6699cc",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "poimandres": {
    label: "Poimandres",
    styles: {
      light: {
        background: "#eef1f6",
        foreground: "#303340",
        card: "#f7f8fb",
        "card-foreground": "#303340",
        popover: "#f7f8fb",
        "popover-foreground": "#303340",
        primary: "#2c9f8c",
        "primary-foreground": "#ffffff",
        secondary: "#e3e6eb",
        "secondary-foreground": "#303340",
        muted: "#e3e6eb",
        "muted-foreground": "#80838c",
        accent: "#d2e8e7",
        "accent-foreground": "#303340",
        destructive: "#c25d8f",
        "destructive-foreground": "#ffffff",
        border: "#d4d6db",
        input: "#d4d6db",
        ring: "#2c9f8c",
        "chart-1": "#2c9f8c",
        "chart-2": "#3d8fbf",
        "chart-3": "#5a7fb5",
        "chart-4": "#9a6fb0",
        "chart-5": "#c25d8f",
        sidebar: "#e7eaef",
        "sidebar-foreground": "#303340",
        "sidebar-primary": "#2c9f8c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d2e8e7",
        "sidebar-accent-foreground": "#303340",
        "sidebar-border": "#d4d6db",
        "sidebar-ring": "#2c9f8c",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1b1e28",
        foreground: "#a6accd",
        card: "#262933",
        "card-foreground": "#a6accd",
        popover: "#262933",
        "popover-foreground": "#a6accd",
        primary: "#5de4c7",
        "primary-foreground": "#0a0a0a",
        secondary: "#343740",
        "secondary-foreground": "#a6accd",
        muted: "#343740",
        "muted-foreground": "#6c7088",
        accent: "#345a59",
        "accent-foreground": "#a6accd",
        destructive: "#d0679d",
        "destructive-foreground": "#ffffff",
        border: "#3f424a",
        input: "#3f424a",
        ring: "#5de4c7",
        "chart-1": "#5de4c7",
        "chart-2": "#89ddff",
        "chart-3": "#add7ff",
        "chart-4": "#fcc5e9",
        "chart-5": "#f087bd",
        sidebar: "#14171e",
        "sidebar-foreground": "#a6accd",
        "sidebar-primary": "#5de4c7",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#345a59",
        "sidebar-accent-foreground": "#a6accd",
        "sidebar-border": "#3f424a",
        "sidebar-ring": "#5de4c7",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "panda": {
    label: "Panda",
    styles: {
      light: {
        background: "#f5f5f5",
        foreground: "#2a2c2d",
        card: "#fafafa",
        "card-foreground": "#2a2c2d",
        popover: "#fafafa",
        "popover-foreground": "#2a2c2d",
        primary: "#00a292",
        "primary-foreground": "#ffffff",
        secondary: "#eaeaea",
        "secondary-foreground": "#2a2c2d",
        muted: "#eaeaea",
        "muted-foreground": "#7f8081",
        accent: "#cdeae7",
        "accent-foreground": "#2a2c2d",
        destructive: "#ff2c6d",
        "destructive-foreground": "#ffffff",
        border: "#dadada",
        input: "#dadada",
        ring: "#00a292",
        "chart-1": "#00a292",
        "chart-2": "#e0568f",
        "chart-3": "#1a8fe3",
        "chart-4": "#d98328",
        "chart-5": "#8a5cd6",
        sidebar: "#eeeeee",
        "sidebar-foreground": "#2a2c2d",
        "sidebar-primary": "#00a292",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#cdeae7",
        "sidebar-accent-foreground": "#2a2c2d",
        "sidebar-border": "#dadada",
        "sidebar-ring": "#00a292",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#292a2b",
        foreground: "#e6e6e6",
        card: "#343536",
        "card-foreground": "#e6e6e6",
        popover: "#343536",
        "popover-foreground": "#e6e6e6",
        primary: "#19f9d8",
        "primary-foreground": "#0a0a0a",
        secondary: "#414142",
        "secondary-foreground": "#e6e6e6",
        muted: "#414142",
        "muted-foreground": "#979797",
        accent: "#2d6860",
        "accent-foreground": "#e6e6e6",
        destructive: "#ff2c6d",
        "destructive-foreground": "#ffffff",
        border: "#4b4c4d",
        input: "#4b4c4d",
        ring: "#19f9d8",
        "chart-1": "#19f9d8",
        "chart-2": "#ff75b5",
        "chart-3": "#45a9f9",
        "chart-4": "#ffb86c",
        "chart-5": "#b084eb",
        sidebar: "#1f2020",
        "sidebar-foreground": "#e6e6e6",
        "sidebar-primary": "#19f9d8",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#2d6860",
        "sidebar-accent-foreground": "#e6e6e6",
        "sidebar-border": "#4b4c4d",
        "sidebar-ring": "#19f9d8",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "vitesse": {
    label: "Vitesse",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#393a34",
        card: "#ffffff",
        "card-foreground": "#393a34",
        popover: "#ffffff",
        "popover-foreground": "#393a34",
        primary: "#1c6b48",
        "primary-foreground": "#ffffff",
        secondary: "#f4f4f4",
        "secondary-foreground": "#393a34",
        muted: "#f4f4f4",
        "muted-foreground": "#8c8d89",
        accent: "#d6e4de",
        "accent-foreground": "#393a34",
        destructive: "#ab5959",
        "destructive-foreground": "#ffffff",
        border: "#e3e3e3",
        input: "#e3e3e3",
        ring: "#1c6b48",
        "chart-1": "#1c6b48",
        "chart-2": "#296aa3",
        "chart-3": "#2993a3",
        "chart-4": "#bd6a3f",
        "chart-5": "#bda437",
        sidebar: "#f7f7f7",
        "sidebar-foreground": "#393a34",
        "sidebar-primary": "#1c6b48",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d6e4de",
        "sidebar-accent-foreground": "#393a34",
        "sidebar-border": "#e3e3e3",
        "sidebar-ring": "#1c6b48",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#121212",
        foreground: "#dbd7ca",
        card: "#1e1e1e",
        "card-foreground": "#dbd7ca",
        popover: "#1e1e1e",
        "popover-foreground": "#dbd7ca",
        primary: "#4d9375",
        "primary-foreground": "#ffffff",
        secondary: "#2c2c2c",
        "secondary-foreground": "#dbd7ca",
        muted: "#2c2c2c",
        "muted-foreground": "#87847d",
        accent: "#2a3c35",
        "accent-foreground": "#dbd7ca",
        destructive: "#cb7676",
        "destructive-foreground": "#ffffff",
        border: "#383838",
        input: "#383838",
        ring: "#4d9375",
        "chart-1": "#4d9375",
        "chart-2": "#6394bf",
        "chart-3": "#5eaab5",
        "chart-4": "#d48f6f",
        "chart-5": "#e0cc77",
        sidebar: "#0e0e0e",
        "sidebar-foreground": "#dbd7ca",
        "sidebar-primary": "#4d9375",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#2a3c35",
        "sidebar-accent-foreground": "#dbd7ca",
        "sidebar-border": "#383838",
        "sidebar-ring": "#4d9375",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "aura": {
    label: "Aura",
    styles: {
      light: {
        background: "#f7f7fb",
        foreground: "#15141b",
        card: "#fbfbfd",
        "card-foreground": "#15141b",
        popover: "#fbfbfd",
        "popover-foreground": "#15141b",
        primary: "#6a3fd6",
        "primary-foreground": "#ffffff",
        secondary: "#ececf0",
        "secondary-foreground": "#15141b",
        muted: "#ececf0",
        "muted-foreground": "#747379",
        accent: "#e1d9f6",
        "accent-foreground": "#15141b",
        destructive: "#d84b4b",
        "destructive-foreground": "#ffffff",
        border: "#dcdcdf",
        input: "#dcdcdf",
        ring: "#6a3fd6",
        "chart-1": "#6a3fd6",
        "chart-2": "#17a17a",
        "chart-3": "#cc7a1f",
        "chart-4": "#2c8fc9",
        "chart-5": "#c24fd0",
        sidebar: "#f0f0f3",
        "sidebar-foreground": "#15141b",
        "sidebar-primary": "#6a3fd6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e1d9f6",
        "sidebar-accent-foreground": "#15141b",
        "sidebar-border": "#dcdcdf",
        "sidebar-ring": "#6a3fd6",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#15141b",
        foreground: "#edecee",
        card: "#212026",
        "card-foreground": "#edecee",
        popover: "#212026",
        "popover-foreground": "#edecee",
        primary: "#a277ff",
        "primary-foreground": "#ffffff",
        secondary: "#2f2e34",
        "secondary-foreground": "#edecee",
        muted: "#2f2e34",
        "muted-foreground": "#929195",
        accent: "#43375e",
        "accent-foreground": "#edecee",
        destructive: "#ff6767",
        "destructive-foreground": "#ffffff",
        border: "#3a3a3f",
        input: "#3a3a3f",
        ring: "#a277ff",
        "chart-1": "#a277ff",
        "chart-2": "#61ffca",
        "chart-3": "#ffca85",
        "chart-4": "#82e2ff",
        "chart-5": "#f694ff",
        sidebar: "#100f14",
        "sidebar-foreground": "#edecee",
        "sidebar-primary": "#a277ff",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#43375e",
        "sidebar-accent-foreground": "#edecee",
        "sidebar-border": "#3a3a3f",
        "sidebar-ring": "#a277ff",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "zenburn": {
    label: "Zenburn",
    styles: {
      light: {
        background: "#f4f4ec",
        foreground: "#3f3f3f",
        card: "#fafaf6",
        "card-foreground": "#3f3f3f",
        popover: "#fafaf6",
        "popover-foreground": "#3f3f3f",
        primary: "#4d7a7d",
        "primary-foreground": "#ffffff",
        secondary: "#e9e9e1",
        "secondary-foreground": "#3f3f3f",
        muted: "#e9e9e1",
        "muted-foreground": "#8b8b88",
        accent: "#dbe3e0",
        "accent-foreground": "#3f3f3f",
        destructive: "#a15c5c",
        "destructive-foreground": "#ffffff",
        border: "#d9d9d2",
        input: "#d9d9d2",
        ring: "#4d7a7d",
        "chart-1": "#4d7a7d",
        "chart-2": "#a5764f",
        "chart-3": "#8a7f2f",
        "chart-4": "#5c7a5c",
        "chart-5": "#97588a",
        sidebar: "#edede5",
        "sidebar-foreground": "#3f3f3f",
        "sidebar-primary": "#4d7a7d",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#dbe3e0",
        "sidebar-accent-foreground": "#3f3f3f",
        "sidebar-border": "#d9d9d2",
        "sidebar-ring": "#4d7a7d",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#3f3f3f",
        foreground: "#dcdccc",
        card: "#494949",
        "card-foreground": "#dcdccc",
        popover: "#494949",
        "popover-foreground": "#dcdccc",
        primary: "#8cd0d3",
        "primary-foreground": "#0a0a0a",
        secondary: "#545454",
        "secondary-foreground": "#dcdccc",
        muted: "#545454",
        "muted-foreground": "#9a9a91",
        accent: "#5a6c6d",
        "accent-foreground": "#dcdccc",
        destructive: "#cc9393",
        "destructive-foreground": "#0a0a0a",
        border: "#5e5e5e",
        input: "#5e5e5e",
        ring: "#8cd0d3",
        "chart-1": "#8cd0d3",
        "chart-2": "#dfaf8f",
        "chart-3": "#f0dfaf",
        "chart-4": "#7f9f7f",
        "chart-5": "#dc8cc3",
        sidebar: "#2f2f2f",
        "sidebar-foreground": "#dcdccc",
        "sidebar-primary": "#8cd0d3",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#5a6c6d",
        "sidebar-accent-foreground": "#dcdccc",
        "sidebar-border": "#5e5e5e",
        "sidebar-ring": "#8cd0d3",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "nightfox": {
    label: "Nightfox",
    styles: {
      light: {
        background: "#f6f2ee",
        foreground: "#352c24",
        card: "#fbf9f7",
        "card-foreground": "#352c24",
        popover: "#fbf9f7",
        "popover-foreground": "#352c24",
        primary: "#2848a9",
        "primary-foreground": "#ffffff",
        secondary: "#ebe7e3",
        "secondary-foreground": "#352c24",
        muted: "#ebe7e3",
        "muted-foreground": "#867f79",
        accent: "#d5d9e9",
        "accent-foreground": "#352c24",
        destructive: "#a5222f",
        "destructive-foreground": "#ffffff",
        border: "#dbd7d4",
        input: "#dbd7d4",
        ring: "#2848a9",
        "chart-1": "#2848a9",
        "chart-2": "#6e33ce",
        "chart-3": "#287980",
        "chart-4": "#396847",
        "chart-5": "#ac5402",
        sidebar: "#efebe7",
        "sidebar-foreground": "#352c24",
        "sidebar-primary": "#2848a9",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d5d9e9",
        "sidebar-accent-foreground": "#352c24",
        "sidebar-border": "#dbd7d4",
        "sidebar-ring": "#2848a9",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#192330",
        foreground: "#cdcecf",
        card: "#252e3a",
        "card-foreground": "#cdcecf",
        popover: "#252e3a",
        "popover-foreground": "#cdcecf",
        primary: "#719cd6",
        "primary-foreground": "#ffffff",
        secondary: "#323b47",
        "secondary-foreground": "#cdcecf",
        muted: "#323b47",
        "muted-foreground": "#81868c",
        accent: "#394b63",
        "accent-foreground": "#cdcecf",
        destructive: "#c94f6d",
        "destructive-foreground": "#ffffff",
        border: "#3e4651",
        input: "#3e4651",
        ring: "#719cd6",
        "chart-1": "#719cd6",
        "chart-2": "#9d79d6",
        "chart-3": "#63cdcf",
        "chart-4": "#81b29a",
        "chart-5": "#dbc074",
        sidebar: "#131a24",
        "sidebar-foreground": "#cdcecf",
        "sidebar-primary": "#719cd6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#394b63",
        "sidebar-accent-foreground": "#cdcecf",
        "sidebar-border": "#3e4651",
        "sidebar-ring": "#719cd6",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "iceberg": {
    label: "Iceberg",
    styles: {
      light: {
        background: "#e8e9ec",
        foreground: "#33374c",
        card: "#f4f4f6",
        "card-foreground": "#33374c",
        popover: "#f4f4f6",
        "popover-foreground": "#33374c",
        primary: "#2d539e",
        "primary-foreground": "#ffffff",
        secondary: "#dedfe1",
        "secondary-foreground": "#33374c",
        muted: "#dedfe1",
        "muted-foreground": "#7f828f",
        accent: "#d0d7e6",
        "accent-foreground": "#33374c",
        destructive: "#cc517a",
        "destructive-foreground": "#ffffff",
        border: "#cecfd2",
        input: "#cecfd2",
        ring: "#2d539e",
        "chart-1": "#2d539e",
        "chart-2": "#3f83a6",
        "chart-3": "#668e3d",
        "chart-4": "#c57339",
        "chart-5": "#7759b4",
        sidebar: "#e1e2e5",
        "sidebar-foreground": "#33374c",
        "sidebar-primary": "#2d539e",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d0d7e6",
        "sidebar-accent-foreground": "#33374c",
        "sidebar-border": "#cecfd2",
        "sidebar-ring": "#2d539e",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#161821",
        foreground: "#c6c8d1",
        card: "#22242c",
        "card-foreground": "#c6c8d1",
        popover: "#22242c",
        "popover-foreground": "#c6c8d1",
        primary: "#84a0c6",
        "primary-foreground": "#ffffff",
        secondary: "#303139",
        "secondary-foreground": "#c6c8d1",
        muted: "#303139",
        "muted-foreground": "#7c7e87",
        accent: "#3b4454",
        "accent-foreground": "#c6c8d1",
        destructive: "#e27878",
        "destructive-foreground": "#ffffff",
        border: "#3b3d45",
        input: "#3b3d45",
        ring: "#84a0c6",
        "chart-1": "#84a0c6",
        "chart-2": "#89b8c2",
        "chart-3": "#b4be82",
        "chart-4": "#e2a478",
        "chart-5": "#a093c7",
        sidebar: "#111219",
        "sidebar-foreground": "#c6c8d1",
        "sidebar-primary": "#84a0c6",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#3b4454",
        "sidebar-accent-foreground": "#c6c8d1",
        "sidebar-border": "#3b3d45",
        "sidebar-ring": "#84a0c6",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "andromeda": {
    label: "Andromeda",
    styles: {
      light: {
        background: "#f4f4f6",
        foreground: "#23262e",
        card: "#fafafb",
        "card-foreground": "#23262e",
        popover: "#fafafb",
        "popover-foreground": "#23262e",
        primary: "#0f9e8c",
        "primary-foreground": "#ffffff",
        secondary: "#e9e9eb",
        "secondary-foreground": "#23262e",
        muted: "#e9e9eb",
        "muted-foreground": "#7b7d82",
        accent: "#d0e9e7",
        "accent-foreground": "#23262e",
        destructive: "#d94a34",
        "destructive-foreground": "#ffffff",
        border: "#d9d9db",
        input: "#d9d9db",
        ring: "#0f9e8c",
        "chart-1": "#0f9e8c",
        "chart-2": "#9b3fd4",
        "chart-3": "#4f9e2f",
        "chart-4": "#c99a15",
        "chart-5": "#d6246a",
        sidebar: "#ededef",
        "sidebar-foreground": "#23262e",
        "sidebar-primary": "#0f9e8c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d0e9e7",
        "sidebar-accent-foreground": "#23262e",
        "sidebar-border": "#d9d9db",
        "sidebar-ring": "#0f9e8c",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#23262e",
        foreground: "#d5ced9",
        card: "#2e3138",
        "card-foreground": "#d5ced9",
        popover: "#2e3138",
        "popover-foreground": "#d5ced9",
        primary: "#00e8c6",
        "primary-foreground": "#0a0a0a",
        secondary: "#3b3e45",
        "secondary-foreground": "#d5ced9",
        muted: "#3b3e45",
        "muted-foreground": "#8a8791",
        accent: "#22615d",
        "accent-foreground": "#d5ced9",
        destructive: "#ee5d43",
        "destructive-foreground": "#ffffff",
        border: "#46494f",
        input: "#46494f",
        ring: "#00e8c6",
        "chart-1": "#00e8c6",
        "chart-2": "#c74ded",
        "chart-3": "#96e072",
        "chart-4": "#ffe66d",
        "chart-5": "#f92672",
        sidebar: "#1a1d23",
        "sidebar-foreground": "#d5ced9",
        "sidebar-primary": "#00e8c6",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#22615d",
        "sidebar-accent-foreground": "#d5ced9",
        "sidebar-border": "#46494f",
        "sidebar-ring": "#00e8c6",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "shades-of-purple": {
    label: "Shades of Purple",
    styles: {
      light: {
        background: "#f6f6fb",
        foreground: "#2d2b55",
        card: "#fbfbfd",
        "card-foreground": "#2d2b55",
        popover: "#fbfbfd",
        "popover-foreground": "#2d2b55",
        primary: "#7c4dff",
        "primary-foreground": "#ffffff",
        secondary: "#ebebf0",
        "secondary-foreground": "#2d2b55",
        muted: "#ebebf0",
        "muted-foreground": "#81809b",
        accent: "#e4dcfd",
        "accent-foreground": "#2d2b55",
        destructive: "#e0245e",
        "destructive-foreground": "#ffffff",
        border: "#dbdbdf",
        input: "#dbdbdf",
        ring: "#7c4dff",
        "chart-1": "#7c4dff",
        "chart-2": "#0aa6b5",
        "chart-3": "#e0246b",
        "chart-4": "#8a7fd6",
        "chart-5": "#a136d6",
        sidebar: "#efeff3",
        "sidebar-foreground": "#2d2b55",
        "sidebar-primary": "#7c4dff",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e4dcfd",
        "sidebar-accent-foreground": "#2d2b55",
        "sidebar-border": "#dbdbdf",
        "sidebar-ring": "#7c4dff",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#2d2b55",
        foreground: "#ffffff",
        card: "#38365e",
        "card-foreground": "#ffffff",
        popover: "#38365e",
        "popover-foreground": "#ffffff",
        primary: "#fad000",
        "primary-foreground": "#0a0a0a",
        secondary: "#444268",
        "secondary-foreground": "#ffffff",
        muted: "#444268",
        "muted-foreground": "#a7a6b8",
        accent: "#6a5e46",
        "accent-foreground": "#ffffff",
        destructive: "#ec3a37",
        "destructive-foreground": "#ffffff",
        border: "#4f4d70",
        input: "#4f4d70",
        ring: "#fad000",
        "chart-1": "#fad000",
        "chart-2": "#9effff",
        "chart-3": "#ff628c",
        "chart-4": "#a599e9",
        "chart-5": "#b362ff",
        sidebar: "#222040",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#fad000",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#6a5e46",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#4f4d70",
        "sidebar-ring": "#fad000",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.5rem",
      }
    }
  },

  "vesper": {
    label: "Vesper",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#101010",
        card: "#ffffff",
        "card-foreground": "#101010",
        popover: "#ffffff",
        "popover-foreground": "#101010",
        primary: "#c26a2b",
        "primary-foreground": "#ffffff",
        secondary: "#f4f4f4",
        "secondary-foreground": "#101010",
        muted: "#f4f4f4",
        "muted-foreground": "#747474",
        accent: "#f4e4d9",
        "accent-foreground": "#101010",
        destructive: "#c14444",
        "destructive-foreground": "#ffffff",
        border: "#e3e3e3",
        input: "#e3e3e3",
        ring: "#c26a2b",
        "chart-1": "#c26a2b",
        "chart-2": "#1f9e88",
        "chart-3": "#c14444",
        "chart-4": "#6b6b6b",
        "chart-5": "#2f8c96",
        sidebar: "#f7f7f7",
        "sidebar-foreground": "#101010",
        "sidebar-primary": "#c26a2b",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f4e4d9",
        "sidebar-accent-foreground": "#101010",
        "sidebar-border": "#e3e3e3",
        "sidebar-ring": "#c26a2b",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.375rem",
      },
      dark: {
        background: "#101010",
        foreground: "#e6e6e6",
        card: "#1c1c1c",
        "card-foreground": "#e6e6e6",
        popover: "#1c1c1c",
        "popover-foreground": "#e6e6e6",
        primary: "#ffc799",
        "primary-foreground": "#0a0a0a",
        secondary: "#2a2a2a",
        "secondary-foreground": "#e6e6e6",
        muted: "#2a2a2a",
        "muted-foreground": "#8c8c8c",
        accent: "#57483d",
        "accent-foreground": "#e6e6e6",
        destructive: "#ff8080",
        "destructive-foreground": "#0a0a0a",
        border: "#363636",
        input: "#363636",
        ring: "#ffc799",
        "chart-1": "#ffc799",
        "chart-2": "#99ffe4",
        "chart-3": "#ff8080",
        "chart-4": "#a0a0a0",
        "chart-5": "#65b8c1",
        sidebar: "#0c0c0c",
        "sidebar-foreground": "#e6e6e6",
        "sidebar-primary": "#ffc799",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#57483d",
        "sidebar-accent-foreground": "#e6e6e6",
        "sidebar-border": "#363636",
        "sidebar-ring": "#ffc799",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-serif": "Georgia, Cambria, \"Times New Roman\", Times, serif",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
        radius: "0.375rem",
      }
    }
  }
};
